import type { Listing } from "@/domain/types";

const hoursAgo = (h: number) => new Date(Date.now() - h * 3600_000).toISOString();

/** Demo-mode seed data: Amsterdam neighborhoods, approximate coordinates. */
export function seedListings(): Listing[] {
  return [
    {
      id: "seed-roses-jordaan",
      seller: { id: "seed-user-1", displayName: "Mila", contact: "@mila_ams" },
      title: "Blush pink roses, barely a day old",
      description:
        "Got these gorgeous roses yesterday but I fly out tonight. 11 stems, opened beautifully. Come grab them before the airport does.",
      priceCents: 800,
      currency: "EUR",
      flowerTypes: ["roses"],
      photos: [{ id: "p1", src: "/seed/roses.svg", position: 0 }],
      freshness: {
        score: 94,
        remainingDaysMin: 5,
        remainingDaysMax: 6,
        confidence: 83,
        signals: ["healthy petals", "green leaves", "no browning", "stems appear fresh"],
      },
      analysis: {
        flowers: [{ type: "roses", name: "Roses", count: 11 }],
        colorPalette: ["blush pink", "cream"],
        damageNotes: [],
        suggestedTitle: "Blush pink roses",
        suggestedDescription: "11 fresh roses looking for a new home.",
        photoQuality: "excellent",
        listingQuality: "excellent",
        suggestions: [],
      },
      neighborhood: "Jordaan",
      coordinates: { lat: 52.3739, lng: 4.8809 },
      pickupMethods: ["meet", "doorstep"],
      status: "active",
      createdAt: hoursAgo(3),
      soldAt: null,
    },
    {
      id: "seed-tulips-pijp",
      seller: { id: "seed-user-2", displayName: "Jesse", contact: "+31 6 1234 5678" },
      title: "Bright yellow tulips from the market",
      description:
        "Bought too many at Albert Cuyp this morning. 15 stems, still tight buds — they'll open over the week.",
      priceCents: 500,
      currency: "EUR",
      flowerTypes: ["tulips"],
      photos: [{ id: "p1", src: "/seed/tulips.svg", position: 0 }],
      freshness: {
        score: 97,
        remainingDaysMin: 6,
        remainingDaysMax: 8,
        confidence: 88,
        signals: ["tight fresh buds", "crisp green stems", "no wilting"],
      },
      analysis: {
        flowers: [{ type: "tulips", name: "Tulips", count: 15 }],
        colorPalette: ["yellow"],
        damageNotes: [],
        suggestedTitle: "Yellow tulips",
        suggestedDescription: "15 market-fresh tulips.",
        photoQuality: "good",
        listingQuality: "excellent",
        suggestions: [],
      },
      neighborhood: "De Pijp",
      coordinates: { lat: 52.3547, lng: 4.8921 },
      pickupMethods: ["meet"],
      status: "active",
      createdAt: hoursAgo(6),
      soldAt: null,
    },
    {
      id: "seed-peonies-oudwest",
      seller: { id: "seed-user-3", displayName: "Sanne", contact: "@sanne_flwr" },
      title: "Peonies in full bloom — enjoy this weekend",
      description:
        "Anniversary peonies, fully open and spectacular right now. Best enjoyed in the next few days. We're off to Portugal.",
      priceCents: 600,
      currency: "EUR",
      flowerTypes: ["peonies"],
      photos: [{ id: "p1", src: "/seed/peonies.svg", position: 0 }],
      freshness: {
        score: 68,
        remainingDaysMin: 2,
        remainingDaysMax: 3,
        confidence: 79,
        signals: ["fully open blooms", "slight softening on outer petals", "leaves still green"],
      },
      analysis: {
        flowers: [{ type: "peonies", name: "Peonies", count: 7 }],
        colorPalette: ["pink", "white"],
        damageNotes: [],
        suggestedTitle: "Peonies in full bloom",
        suggestedDescription: "7 open peonies at their peak.",
        photoQuality: "good",
        listingQuality: "good",
        suggestions: [],
      },
      neighborhood: "Oud-West",
      coordinates: { lat: 52.3676, lng: 4.8672 },
      pickupMethods: ["doorstep"],
      status: "active",
      createdAt: hoursAgo(26),
      soldAt: null,
    },
    {
      id: "seed-mixed-centrum",
      seller: { id: "seed-user-4", displayName: "Tom", contact: "+31 6 8765 4321" },
      title: "Big mixed bouquet from a company event",
      description:
        "Centerpiece from yesterday's office party. Roses, lilies and chrysanthemums. Huge — bring two hands.",
      priceCents: 1000,
      currency: "EUR",
      flowerTypes: ["mixed", "roses", "lilies", "chrysanthemums"],
      photos: [{ id: "p1", src: "/seed/mixed.svg", position: 0 }],
      freshness: {
        score: 82,
        remainingDaysMin: 4,
        remainingDaysMax: 5,
        confidence: 75,
        signals: ["most blooms firm", "lilies just opening", "minor edge browning on roses"],
      },
      analysis: {
        flowers: [
          { type: "roses", name: "Roses", count: 6 },
          { type: "lilies", name: "Lilies", count: 4 },
          { type: "chrysanthemums", name: "Chrysanthemums", count: 5 },
        ],
        colorPalette: ["white", "red", "green"],
        damageNotes: ["minor edge browning on two roses"],
        suggestedTitle: "Mixed bouquet with roses",
        suggestedDescription: "Large event bouquet with roses, lilies and chrysanthemums.",
        photoQuality: "average",
        listingQuality: "good",
        suggestions: ["Improve lighting — daylight near a window works best."],
      },
      neighborhood: "Centrum",
      coordinates: { lat: 52.3728, lng: 4.8936 },
      pickupMethods: ["meet", "pickup_point"],
      status: "active",
      createdAt: hoursAgo(20),
      soldAt: null,
    },
    {
      id: "seed-hydrangeas-oost",
      seller: { id: "seed-user-5", displayName: "Femke", contact: "@femke_oost" },
      title: "Blue hydrangeas, need water soon",
      description:
        "Three big hydrangea heads. Moving apartments Saturday and can't take them. Free vase included if you want it.",
      priceCents: 300,
      currency: "EUR",
      flowerTypes: ["hydrangeas"],
      photos: [{ id: "p1", src: "/seed/hydrangeas.svg", position: 0 }],
      freshness: {
        score: 55,
        remainingDaysMin: 1,
        remainingDaysMax: 2,
        confidence: 72,
        signals: ["some petals papery at edges", "heads slightly drooping", "stems need a fresh cut"],
      },
      analysis: {
        flowers: [{ type: "hydrangeas", name: "Hydrangeas", count: 3 }],
        colorPalette: ["blue", "lavender"],
        damageNotes: ["drooping on one head"],
        suggestedTitle: "Blue hydrangeas",
        suggestedDescription: "Three hydrangea heads, need water soon.",
        photoQuality: "good",
        listingQuality: "average",
        suggestions: ["Flowers appear partially wilted — a fresh stem cut may help before handover."],
      },
      neighborhood: "Oost",
      coordinates: { lat: 52.3625, lng: 4.9296 },
      pickupMethods: ["doorstep"],
      status: "active",
      createdAt: hoursAgo(44),
      soldAt: null,
    },
    {
      id: "seed-sunflowers-noord",
      seller: { id: "seed-user-6", displayName: "Daan", contact: "+31 6 2468 1357" },
      title: "Sunflowers — sold, enjoy them Lisa!",
      description: "Nine tall sunflowers from the ferry market.",
      priceCents: 450,
      currency: "EUR",
      flowerTypes: ["sunflowers"],
      photos: [{ id: "p1", src: "/seed/sunflowers.svg", position: 0 }],
      freshness: {
        score: 90,
        remainingDaysMin: 5,
        remainingDaysMax: 7,
        confidence: 85,
        signals: ["firm petals", "strong stems", "vivid color"],
      },
      analysis: null,
      neighborhood: "Noord",
      coordinates: { lat: 52.3907, lng: 4.9163 },
      pickupMethods: ["meet"],
      status: "sold",
      createdAt: hoursAgo(50),
      soldAt: hoursAgo(8),
    },
  ];
}
